services:
  n8n:
    image: n8nio/n8n
    restart: always

    ports:
      - "127.0.0.1:5678:5678"

    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https

      - N8N_EDITOR_BASE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/

      - N8N_PROXY_HOPS=1

      - NODE_ENV=production

      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}

      - N8N_RESTRICT_FILE_ACCESS_TO=/files
      - N8N_ENABLE_EXECUTE_COMMAND=true
      - NODES_EXCLUDE=[]

      - N8N_LOG_LEVEL=debug

    volumes:
      - n8n_data:/home/node/.n8n
      - /Users/tanvi/files:/files

volumes:
  n8n_data: